name: Update VPNGate List

on:
  schedule:
    - cron: '*/10 * * * *'  # 每10分钟运行一次
  push:
    branches:
      - main

jobs:
  update-list:
    runs-on: ubuntu-latest

    steps:
    # Step 1: 检出代码
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: 设置 Python 环境
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'  # 使用最新稳定版 Python
        # cache: 'pip'  # 缓存 pip 依赖

    # Step 3: 安装依赖
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install requests

    # Step 4: 拉取并更新 VPNGate 数据
    - name: Fetch VPNGate data and update CSV
      run: python fetch_vpngate.py

    # Step 5: 提交并推送更新
    - name: Commit and push changes
      uses: EndBug/add-and-commit@v9
      with:
        message: "Update VPNGate list"
        add: "servers.csv"