name: Update VPNGate List

on:
  schedule:
    - cron: '*/10 * * * *'  # 每10分钟运行一次
  push:
    branches:
      - main

jobs:
  update-list:
    runs-on: ubuntu-latest

    steps:
    # Step 1: 检出代码
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: 设置 Python 环境
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'  # 使用最新稳定版 Python
        # cache: 'pip'  # 缓存 pip 依赖

    # Step 3: 动态创建 requirements.txt
    - name: Create requirements.txt
      run: |
        pip install pipreq
        pipreq .
        # echo "requests>=2.28.0" > requirements.txt

    # Step 4: 安装依赖
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    # Step 5: 拉取并更新 VPNGate 数据
    - name: Fetch VPNGate data and update CSV
      run: python fetch_vpngate.py

    # Step 6: 修改 README.md 文件
    - name: Update README.md
      run: |
        echo "# $(basename $GITHUB_REPOSITORY)" > README.md
        echo "" >> README.md
        echo "The servers.csv file was last updated on $(date -u +"%Y-%m-%d %H:%M:%S") UTC." >> README.md

    # Step 7: 提交并推送更新
    - name: Commit and push changes
      uses: EndBug/add-and-commit@v9
      with:
        message: "Update servers.csv and README.md"
        add: |
          requirements.txt
          servers.csv
          README.md